# Generated by Django 5.0.6 on 2024-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_cadastro', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('usuario', models.CharField(max_length=30, verbose_name='Usuário')),
                ('senha', models.CharField(max_length=65, verbose_name='Senha')),
            ],
        ),
    ]
